#!/bin/bash

mode=${2-3}			# 1: mag 2: time mag 3: AE
n=${2-100000}



seed=-1

mag_c=2
mres=0.01
mag_corner=8
beta=0.666666666666666666	# 2/3 b

random_tgr_mag $n $seed $beta $mag_c $mag_corner > tmp.dat
if [ $mode = 1 ];then

    
    pshistogram tmp.dat -JX10/6l -W0.25 -L0.5 -G128 -Z0 -P -Ba1f.25:"magnitude":/a2f3:"number": > tmp.ps
    modifybb tmp.ps 1
#gv tmp.pdf
    
    cat tmp.dat | calc_gr $mres $mag_c 4 
    gzip -c tmp.dat > ~/Dropbox/tmp/tnp.gz
    
    rm tmp.dat
elif [ $mode = 2 ];then		# time dep synthetic
    ((seed=seed-1))
    random $n $seed > tmp.2
    paste tmp.2 tmp.dat | gawk '{t+=($1*10+0.1);printf("%e %.2f\n",t,$2)}' > tmp.3
    cat tmp.3 | calc_gr_time 700 $mres $mag_c > tmp.dat
    cat <<EOF | gnuplot
set term post enh color solid
set out 'tmp.ps'
set xlabel 'time'
set ylabel 'b value'
plot 'tmp.dat' using 1 : 2 title 'Thomas' w l, \
     'tmp.dat' using 1 : 3 title 'b-pos' w l
     
EOF

    rm tmp.dat tmp.2 tmp.3
elif [ $mode = 3 ];then
    #    mag_c=0.75
    mag_c=1.5
    mres=0.01
    # time dep based on AEs
    dir1=$datadir/gfz_lab/2023-003_Kwiatek-and-Goebel_Catalog-Data/
    dir2=$datadir/gfz_lab/2023-003_Kwiatek-and-Goebel_External-Stress-Measurement-Data/
    #    ex=WgN04
    ex=WgN07
    gawk -F, '{if(NR>1)print($2,$7)}' $dir1"/AE_"$ex"_catalog.csv" > tmp.ae

    for dt in 180;do
    #for dt in -1000;do
	cat tmp.ae | calc_gr_time $dt $mres $mag_c  > tmp.b
    done

    
    gawk -F, '{if(NR>1)print($1,$2)}' $dir2"/MTS_"$ex".csv" > tmp.s
    wait

    cat <<EOF | gnuplot
set term post enh color solid
set out 'aeb.ps'
set xlabel 'time [s]'


set xrange [0:13000]

set title '$ex'
#set key bottom spacing 1.2
set multi
set size 1,.5
set origin 0,.5
set ylabel 'stress'
#set ytics (100, 200, 300, 400)
#plot 'tmp.s' title 'stress' w l
plot 'tmp.s' title '' w l
set title ''
set origin 0,0
set yrange [1:1.75]
set ylabel 'b'
plot      'tmp.b' using 1 : 2 axes x1y1 title 'b_T(M_c = $mag_c)' w l ,\
     'tmp.b' using 1 : 3 axes x1y1 title 'b_{+}' w l lw 2
EOF
#    rm tmp*
fi

