#!/bin/bash
#
# given certain region codes, print out parameters
#
# usage: region_parameters region outmode
# 
#
region=${1-0}
#
# 0: normal, many parameters 
# 1: box corners 
# 2: box center 
# 3: -Rregion
# 4: projection
# 5: inc
# 6: ann
# 7: name
# 8: region in w e s n format
# 8b: region in theta_min theta_max phi_min phi_max format (radians)
# 9:  translucent PNG overview map
# 10: detailed map
# 11: normal overview map
# 12: mid point in x
# 13: pscoast resolution
# 14: colatitude (theta) and longitude (phi) in radians
#     thetamin, thetamax, phimin, phimax
# 15: center of region in lon lat
outmode=${2-0}
#
#
lsystem=${3-0}			# 0: 0...360 1: -180...180
#
# regions, incs, and name
#
if [[ $region -eq 0 || $region -eq -1 ]];then # world 
	name=WLD
	reg="0 360 -90 90"
	inc=5
elif [ $region -eq 1 ];then # SAF
	name=SAF
	reg="234 247 31 41"
	inc=0.5
elif [ $region -eq 2 ];then # SAM
	name=SAM
	reg="267 330 -65 22"
	inc=2
elif [ $region -eq 3 ];then # Lau basin
	name=LAU
	reg="172 192 -27 -10"
	inc=1
elif [ $region -eq 4 ];then # North America
	name=NAM
	reg="229.5 294.5 22.5 55"
	inc=0.25
elif [ $region -eq 5 ];then # Phillipines
	name=PHI
	reg="117 153 0 35"
	inc=1.5
elif [ $region -eq 6 ];then # Japan
	name=JAP
	#reg="125 153 30 50"
	reg="127 153 30 50"
	inc=1
elif [ $region -eq 7 ];then # EPR
	name=EPR
	reg="242 251 -20 -14"
	inc=.5
elif [ $region -eq 8 ];then # CAR
	name=CAR
	#reg="265 310 0 25"
	#reg="280 302 3 21"
	#reg="260 310 -20 40"
	#reg="260 310 -20 34"
	reg="-110 -50 -20 34"
	inc=1
elif [ $region -eq 9 ];then # New Zealand
	name=NZL
	#reg="158 184 -55 -29"
	reg="164 180 -47 -33"
	inc=0.5
elif [ $region -eq 10 ];then # Aleutians
	name=ALE
	reg="165 210 45 65"
	inc=1.25
elif [ $region -eq 11 ];then # Ontong Java Plateau
	name=OJP
	reg="145 175 -15 15"
	inc=1.25
elif [ $region -eq 12 ];then # Africa
	name=AFR
	#reg="-22 62 -40 38"
	reg="-35 62 -40 45"
	inc=2.5
elif [ $region -eq 13 ];then # Himalaya
	name=HMY
	reg="60 120 20 50"
	inc=2
elif [ $region -eq 14 ];then # Western North America,2
	name=WNM
	reg="235 250 30 50"
	inc=2
elif [ $region -eq 15 ];then # Asia
	name=ASI
	reg="50 140 15 65"
	inc=2
elif [ $region -eq 16 ];then # EPR, bigger
	name=EP2
	reg="230 268 -34 0"
	inc=1
elif [ $region -eq 17 ];then # North America, big
	name=NAM
	reg="220 310 15 70"
	inc=2
elif [ $region -eq 18 ];then # EPR, biggest
	name=EP3
	reg="236 264 -36 3"
	inc=1
elif [ $region -eq 19 ];then # Indonesia subduction zone
	name=ISD
	#reg="90 137 -12 12"
	reg="90 137 -14 12"
	inc=1
elif [ $region -eq 20 ];then # Central Andes
	name=CAD
	reg="262 312 -30 12"
	inc=1
elif [ $region -eq 21 ];then # Australia
	name=AUS
	reg="100 160 -50 0"
	inc=1
elif [ $region -eq 22 ];then # Italy
	name=ITL
	reg="6 20 36 48"
	inc=2
elif [ $region -eq 23 ];then # southern California
	name=SCL
	reg="239 246 32 37"
#	reg="245 250 32 37"
	inc=0.1
elif [ $region -eq 24 ];then # mediterranean (there's a larger version, too)
    name=MED
#    reg="-10 40 30 50"
    reg="0 40 30 50"
    inc=2
elif [ $region -eq 25 ];then # Hawaii
    name=HAW
    #reg="190 220 15 30"
    reg="190 210 15 30"
    inc=0.1
elif [ $region -eq 26 ];then # Eifel
    name=EFL
    reg="4 11 48 52"
    inc=0.1
elif [ $region -eq 27 ];then # Afar
    name=AFA
    #reg="30 48 -2 30"
    #reg="30 48 2 20"
    reg="20 52 -17 15"
    inc=0.1
elif [ $region -eq 28 ];then # Nevada
    name=NVD
    reg="238 250 34 45"
    inc=0.1
elif [ $region -eq 29 ];then # Iceland
    name=ICE
    reg="331 351 60 70"
    inc=0.1
elif [ $region -eq 30 ];then # World, focus on AFR
    name=WLD
    reg="-180 180 -90 90"
    inc=5
elif [ $region -eq 31 ];then # Antarctica
    name=ANT
    #reg="0 360 -90 -50"
    reg="0 360 -90 -57"
#    reg="0 360 -90 90"
#    reg="-180 180 -90 90"
    inc=1
elif [ $region -eq 32 ];then # larger Western US
    name=WUS
    #reg="233 254 30 50"
    reg="225 254 30 58"

    inc=1
elif [ $region -eq 33 ];then # Greece
    name=GRE
    reg="16 33 33 44"
    inc=1
elif [ $region -eq 34 ];then # Europe
    name=EUR
    reg="-13 45 29 72"
    inc=2
elif [ $region -eq 35 ];then # Socal, high resolution
    name=SCAh
    #reg="239.5 244.5 32 36"
    reg="237 247 30 39"
    inc=0.05
elif [ $region -eq 36 ];then # smaller Socal
    name=SCAs
    reg="239 246 32 38"
    inc=0.5
elif [ $region -eq 37 ];then # Eastern US
    name=eUS
    reg="268 307 25 60"
    inc=0.5
elif [ $region -eq 38 ];then # Arabia
    name=ARA
    reg="30 60 10 40"
    inc=0.5
elif [ $region -eq 39 ];then # Ross sea, Antarctica
    name=RSE
    reg="140 210 -80 -65"
    inc=0.5
elif [ $region -eq 40 ];then # Kimberly
    name=KIM
    reg="20 32 -30 -25"
    inc=0.25
elif [ $region -eq 41 ];then # Yellowstone
    name=YST
    reg="238 262 38 52"
    inc=0.25
elif [ $region -eq 42 ];then # SAF, rotated
    name=SAF
    reg="-7 8 -4 4"
    inc=0.5
elif [ $region -eq 43 ];then # Norway
    name=NRW
    reg="-5 30 55 72"
    inc=0.25
elif [ $region -eq 44 ];then # Pacific
    name=PAC
    reg="130 290 -67.5 62.5"
    inc=0.25
elif [ $region -eq 45 ];then # Taiwan
    name=TAI
    reg="118 124 20 26"
#    reg="120 121.8 22 25.5"
    inc=0.25
elif [ $region -eq 46 ];then # part of Carribean plate Antilles
    name=CPS
#    reg="287 302 5 15"
#    reg="289 304 8 16"
    reg="294 302 8 14"
    inc=0.25
elif [ $region -eq 47 ];then	# marianas
    name=MAR
    reg="135 150 10 25"
    inc=0.25
elif [ $region -eq 48 ];then	# Alboran
    name=ALB
    #reg="-15 2 28 41"
    reg="-20 2 25 41"
    inc=0.25
elif [ $region -eq 49 ];then	# Tyrrhenian
    name=TYR
    reg="10 20 35 45"
    inc=0.25
elif [ $region -eq 50 ];then # smaller CAR
    name=CAR2
#5-22N
#-76 to -57W

#    -R-78/-58/3/13.5
#    reg="282 302 3 13.5"
    reg="-78 -58 3 13.5"
#    reg="275 305 0 25"
    inc=1
elif [ $region -eq 51 ];then # Banda
	name=BAN
	#reg="100 135 -15 10"
	reg="90 135 -16 12"	
	inc=2
elif [ $region -eq 52 ];then # Banda small
	name=BAN2
	#reg="115 135 -12 0"
	#reg="116 134.5 -12 0"
	#reg="114 130 -12 -5"
	#reg="118.5 128 -11.75 -6.75"
	reg="118 128 -11.5 -6.5"
	inc=1
elif [ $region -eq 53 ];then # Tibet/Asia
	name=TIB
	reg="15 150 -20 70"
	inc=1
elif [ $region -eq 54 ];then # Atlantic
    name=ATL
    reg="-80 25 -60 70"
    inc=0.25
elif [ $region -eq 55 ];then # mediterranean (there's a smaller version, too)
    name=ME2
    reg="-35 60 30 75"
    inc=1
elif [ $region -eq 56 ];then # mediterranean v 3, there's an even smaller version used for the review paper
    name=ME3
    reg="-15 65 15 60"
    inc=1
elif [ $region -eq 57 ];then # Tibet2
	name=TIB2
	#reg="70 120 0 50"
	reg="64 115 18 45"
	inc=1
elif [ $region -eq 58 ];then	# Alboran, small
    name=ALB2
    reg="-11 1 29 40"
    inc=0.25
elif [ $region -eq 59 ];then	# North Anatolian
    name=NAF
    #reg="18 45 28 45"
    reg="18 47 32 45"
    inc=0.25
elif [ $region -eq 60 ];then	# Germany
    name=GER
    reg="5 17 45 55.5"
    inc=0.25
elif [ $region -eq 61 ];then	# Iran
    name=IRA
    reg="43 62 25 42"
    inc=0.25
elif [ $region -eq 62 ];then	# Indian ocean for barruol splitting
    name=IOB
    reg="50 80 -25 10"
    inc=0.25
elif [ $region -eq 63 ];then	# Tonga
    name=TON
    reg="172 190 -42 -10"
    inc=0.25
elif [ $region -eq 64 ];then	# Alboran, smallest (Atlas)
    name=ALA
    reg="-12 5 28 36"
    inc=0.25
elif [ $region -eq 65 ];then	# Colombia
    name=COL
    #    reg="-80 -66 -5 14"
    #reg="-82 -66 -7 14"
    reg="-81 -67 -1 14"
    inc=0.25
elif [ $region -eq 66 ];then	# Middle East
    name=MES
    #reg="25 70 5 45"
    #reg="17 50 30 50"
    reg="17 62 20 50"
    inc=0.25
elif [ $region -eq 67 ];then # mediterranean v 4, 
    name=ME4
    reg="-12.5 45 29 50"	# review paper version
    inc=1
elif [ $region -eq 68 ];then # Denali
    name=DEN
    reg="200 220 58 72"	
    inc=1

elif [ $region -eq 69 ];then # NW Africa
    name=NWA
    reg="-20 15 0 30"
#    reg="-18 13 0 29.5"	
    inc=1
elif [ $region -eq 70 ];then # Indian Ocean, differently defined for ridge
    name=IOC
    reg="70 160 -63 -13"	
    inc=1
elif [ $region -eq 71 ];then # Congo basin
    name=CON
    reg="13 34 -12 9"	
    inc=1
elif [ $region -eq 72 ];then # Hudson 
    name=HUD
    reg="-102 -70 50 70"	
    inc=1
elif [ $region -eq 73 ];then # NW PAcific
    name=NWP
    reg="130 170 20 45"
    inc=1
elif [ $region -eq 74 ];then # Madagascar
    name=MDG
    reg="30 60 -35 0"
    inc=0.2
elif [ $region -eq 75 ];then # North Africa
    name=NAR
    reg="-20 55 15 45"
    inc=1
elif [ $region -eq 76  ];then # Cordillera
    name=CDL
    reg="225 327 -60 65"
    inc=2
elif [ $region -eq 77  ];then # western Med
    name=WMD
    reg="-20 20 26 45"
    inc=1
elif [ $region -eq 78  ];then # western Med
    name=CMD
    reg="2 25 35 52"
    inc=1
elif [ $region -eq 79  ];then # Myanmar
    name=MYA
    reg="65 140 -20 40"
    inc=1
elif [ $region -eq 80  ];then # ME4 Azores
    name=ME4
    reg="-40 20 25 50"
    inc=1
elif [ $region -eq 81 ];then # Alps, Apennines, Calabria
    name=CLB
    reg="4 19 36 48.5"
    inc=0.1
elif [ $region -eq 82 ];then # JDF
    name=JDF
    reg="226 244 39 55"
    inc=0.1
elif [ $region -eq 83 ];then # CAP
    name=CAP
    reg="8 19 39 45"
    inc=0.1
elif [ $region -eq 84 ];then	# Anatolian plateau
    name=ANA
    #reg="26 44 35 43"
    reg="26 41 33 41.5"
    inc=0.25
elif [ $region -eq 85 ];then	# Massif Central
    name=MCT
    reg="0.5 5.5 42.5 47"
    inc=0.25
elif [ $region -eq 86 ];then	# iberia
    name=IBR
    reg="-10 4 35.5 44"
    inc=0.25
elif [ $region -eq 87 ];then	# Alps
    name=ALP
    #reg="2 17 42 49"
    reg="4 19 41 49"
    inc=0.25
elif [ $region -eq 88 ];then	# South Africa
    name=sAF
    reg="10 40 -35 -6"
    inc=0.25
elif [ $region -eq 89 ];then # India
    name=IND
    reg="58 102 2 44"
    inc=1
elif [ $region -eq 90 ];then # Japan, bigger (with Chinae
    name=JAP2
    #reg="95 172 0 65"
    reg="105 180 0 60"
    #reg="87 155 9 61"
    inc=1
elif [ $region -eq 91 ];then # Croatia
    name=CRO
    reg="14 20 42 45"
    inc=1
elif [ $region -eq 92 ];then # Nile
    name=NIL
    reg="0 50 4 42"
    inc=1
elif [ $region -eq 93 ];then # East African Rift
    name=EAR 
    reg="26 45 -18 15"
    inc=1
elif [ $region -eq 94 ];then # greater CAR
    name=CAR3
    #    reg="-120 -32.5 -40 50"
    #reg="-120 -40 -30 40"
    reg="-110 -50 -20 34"
    inc=1
elif [ $region -eq 95 ];then # North and South American, Americas, Cordillera
    name=CAR3
    reg="-133 -32.5 -60 53"
    #reg="-120 -40 -30 40"
    inc=1
elif [ $region -eq 96 ];then # Moroc
    name=MOR
    reg="-15 6 28 36"
    inc=1
elif [ $region -eq 97 ];then # Andes
    name=AND
    reg="275 300 -50 15"
    inc=1
elif [ $region -eq 98 ];then # Japan 3 
    name=JAP3
    reg="115 150 25 50"
    inc=1
elif [ $region -eq 99 ];then # Alaska
    name=ALA
    reg="-172 -118 50 74"
    inc=1
elif [ $region -eq 100 ];then # North Cali
    name=nCAL
    reg="-126 -118 35 44"
    inc=1
elif [ $region -eq 101 ];then	# Iran big
    name=IRAb
    reg="21 78 16 47"
    inc=0.25
elif [ $region -eq 102 ];then	# Dead Sea
    name=DST
    reg="34.5 36 30 32"
    inc=0.125
elif [ $region -eq 103 ];then	# Kyushu
    name=KYU
    reg="124 139 25 37"
    inc=0.125
elif [ $region -eq 104 ];then	# Rio Grand Rift
    name=RGR
    reg="-114 -100 28 42"
    inc=0.125
elif [ $region -eq 105 ];then	# Basin and Range
    name=BAR
    reg="-125 -108 34 46"
    inc=0.25
elif [ $region -eq 106 ];then # supper small
    name=SCAS
    reg="-120.80 -120.3 35.84 36.20"
    inc=0.01
elif [ $region -eq 107 ];then # Centralmost Andes / IPOC
    name=IPO
    reg="-71.5 -66 -25 -20"
    #reg="-71.5 -67.25 -24.5 -19.5"
    inc=1
elif [ $region -eq 108 ];then # Nazca
    name=NAZ
    reg="-132 -124 40 52"
    inc=1
elif [ $region -eq 109 ];then # Scandinavia
    name=SKA
    reg="3 40 53 72"
    inc=1
elif [ $region -eq 110 ];then # North America, big for GIA
    name=GIA
    reg="210 330 25 80"
    inc=2
elif [ $region -eq 111 ];then # California (catalog)
    name=CAL
    reg="-128 -112 30 42"
    inc=.1
else
    echo $0: region $region undefined
    exit
fi
if [ $lsystem -eq 1 ];then	# shift
    regt=`echo $reg | gawk '{if(($1==0) && ($2==360)){x=-180;y=180;}else{if($1>180){x=-(360-$1);}else{x=$1};if($2>180){y=-(360-$2);}else{y=$2};}print(x,y,$3,$4)}'`
    reg=$regt
fi


reg1=`echo $reg | gawk '{printf("-R%g/%g/%g/%g",$1,$2,$3,$4)}'`
#
# plotting parameters
#
if [ $region -eq -1 ];then
    proj=-JN0/7
    pscr="-Dc -A50000"
    #ann=-Bg30/g30WesN
    ann=""
elif [ $region -eq 0 ];then
    proj=-JN180/7
    pscr="-Dc -A50000"
    #ann=-Bg30/g30WesN
    ann=""
elif [ $region -eq 2 ];then	# SAM
    #proj=-JH`echo $reg1 | gawk -f reg2midlon.awk`/7
    #    proj=-JN`echo $reg1 | gawk -f reg2midlon.awk`/7
    proj=-JB`echo $reg1 | gawk -f reg2midlon.awk`/`echo $reg1 | gawk -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.33 -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.66 -f reg2midlat.awk`/8
    pscr="-Di -A5000"
    ann=-Ba20f2WesN
elif [[ $region -eq 6  ]];then # japan
    proj=-JM7
    pscr="-Di -A5000"
    ann=-Ba4f2WesN
elif [[ $region -eq 90 ]];then # japan, big
    #proj=-JH`echo $reg1 | gawk -f reg2midlon.awk`/7
    proj=-JM7
    pscr="-Df -A5000"
    ann=-Ba10f2WesN
elif [ $region -eq 30 ];then
    proj=-JN0/7
    pscr=-Dc
    ann=-Bg30/g30WesN
elif [[ $region -eq 9  || $region -eq 1  ]];then
    pscr=-Df
    proj=-JM7
    ann=-Ba2f.2WesN
elif [ $region -eq 8 ];then
    pscr=-Df
    proj=-JM7
    ann=-Ba10f1WesN
elif [ $region -eq 11 ];then
    pscr=-Df
    proj=-JQ160/7
    ann=-Ba10f5WesN
elif [ $region -eq 12 ];then # Africa
    pscr=-Di
    proj=-JH15/7
    ann=-Ba20f5WesN
elif [ $region -eq 13 ];then # Himalaya
    pscr=-Df
    proj=-JH90/7
    ann=-Ba10f5WesN
elif [ $region -eq 14 ];then # Western US, 2
    pscr=-Df
    proj=-JQ245.5/7
    ann=-Ba5f1WeSn
elif [ $region -eq 17 ];then # larger US
    pscr="-Di -A5000"
    #proj=-JB`echo $reg1 | gawk -f reg2midlon.awk`/`echo $reg1 | gawk -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.33 -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.66 -f reg2midlat.awk`/7
    #proj=-JL265/42.5/28.33/51.66/7
    #proj=-JQ265/42.5/7
    #proj=-JH`echo $reg1 | gawk -f reg2midlon.awk`/7
    proj=-JM7
    ann=-Ba20f2WesN
elif [ $region -eq 12 ];then # Africa
    pscr=-Di
    proj=-JH15/7
    ann=-Ba10f5WesN
elif [ $region -eq 15 ];then # Asia
    pscr=-Di
    proj=-JH95/9.75
    ann=-Ba6f2WeSn
elif [[ $region -eq 7 || $region -eq 40 ]];then # EPR or Kim
    pscr=-Df
    proj=-JM7
    ann=-Ba2f1WeSn
elif [ $region -eq 18 ];then # EPR, 3
    pscr=-Df
    proj=-JH248/7
    ann=-Ba2f1WeSn
elif [ $region -eq 19 ];then # Indonesia
    pscr=-Dh
    proj=-JH`echo $reg1 | gawk -f reg2midlon.awk`/7
    ann=-Ba10f2WeSn
elif [ $region -eq 20 ];then # Central Andes
    pscr=-Df
    proj=-JH294/7
    ann=-Ba2f1WeSn
elif [ $region -eq 21 ];then # Australia
    pscr=-Di
    proj=-JH130/7
#    proj=-JM7
    ann=-Ba10f2/a10f2WeSn
elif [ $region -eq 22 ];then # Italy
    pscr=-Df
    ann=-Ba2f1WeSn
    proj=-JM7
elif [ $region -eq 23 ];then # southern cali
    pscr=-Df
    ann=-Ba2f.2WeSn
    proj=-JH242.5/7
elif [ $region -eq 24 ];then # med
    pscr=-Di
    proj=-JH15/7
    ann=-Ba5f1WeSn
elif [ $region -eq 25 ];then # Hawaii
    pscr="-Df -A1000"
    ann=-Ba4f2WesN
    proj=-JM7
elif [ $region -eq 26 ];then	# Eifel
    pscr=-Df
    proj=-JM7
    ann=-Ba1f.2WesN
elif [ $region -eq 27 ];then	# Afar
    pscr="-Df -A5000"
    proj=-JM7
    ann=-Ba2f1WesN
elif [ $region -eq 29 ];then # Iceland
    pscr="-Df -A1000"
    ann=-Ba2f1WesN
    proj=-JM7
elif [ $region -eq 4 ];then	# NAM
    pscr="-Df -A5000"
    #proj=-JH`echo $reg1 | gawk -f reg2midlon.awk`/12
    proj=-JB`echo $reg1 | gawk -f reg2midlon.awk`/`echo $reg1 | gawk -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.33 -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.66 -f reg2midlat.awk`/8
    ann=-Ba10f2WesN
elif [ $region -eq 37 ];then	# eUS
    pscr="-Df -A5000"
    proj=-JM7
    ann=-Ba4f2WesN
elif [ $region -eq 41 ];then	# YST
    pscr="-Df -A5000"
    proj=-JM7
    ann=-Ba4f2WesN
elif [ $region -eq 43 ];then	# NRW
    pscr=-Di
    proj=-JN12.5/7
    ann=-Ba5f1WeSn
elif [[ $region -ge 25 && $region -le 29 ]];then # hotspots
    pscr=-Df
    proj=-JM7
    ann=-Ba5f1WeSn
elif [ $region -eq 31 ];then	# Antarctica
    pscr=-Df
#    proj=-JS0/-90/6
    proj=-JA0/-90/6
#    ann=-Ba20f5g20/a20f5g20WESN
    ann=-Bf30a30g30
elif [ $region -eq 32 ];then 	# larger Western US
    ann=-Ba4f2WesN
#    proj=-JH242/7
#    proj=-JM7
#    proj=-JB-118/39/36/42/7
#    proj=-JB244.5/39/36/42/7
    proj=-JM242.5/7
    #pscr="-Dh -N1 -N2"
    pscr="-Dh -A5000"
    
elif [ $region -eq 34 ];then 	# EUR
    ann=-Ba20f2WeSn
    proj=-JB`echo $reg1 | gawk -f reg2midlon.awk`/`echo $reg1 | gawk -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.33 -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.66 -f reg2midlat.awk`/9
    #proj=-JH17.5/7
    pscr="-Di -A5000" # -N1 -N2"
elif [ $region -eq 35 ];then 	# SoCal
    ann=-Ba1f.2WeSn
    proj=-JM7
    pscr="-Dh -N1 -N2"
elif [ $region -eq 37 ];then 	# eastern us
    ann=-Ba5f1WeSn
    proj=-JH275/7
    pscr="-Di -A5000 -N1 -N2"
elif [ $region -eq 38 ];then 	# ARA
    ann=-Ba5f1WeSn
    proj=-JH45/7
    pscr="-Dh -N1 -N2"
elif [ $region -eq 39 ];then 	# ross sea
    ann=-Ba5f1WesN
    proj=-JH172.5/7
#    proj=-JM7
    pscr="-Df -N1 -N2"
elif [ $region -eq 42 ];then	# SAF, rotated
    pscr=-Df
    proj=-JOa240/35.1/140/7
    ann=-Ba5g5f1WeSn
elif [ $region -eq 44 ];then	# PAC
    pscr="-Di -A500"
    proj=-JW`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    ann=-Ba30f5WesN
elif [[ $region -eq 45 || $region -eq 46 ]];then	# TAI
    pscr=-Df
    proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/8
    #proj=-JM7
    ann=-Ba2f.2WeSn
elif [ $region -eq 48 ];then
    ann=-Ba5f1wESn
    proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    pscr="-Dh"
elif [ $region -eq 51 ];then	# Banda
    pscr="-Dh -A5000"
    proj=-JM7
    ann=-Ba4f2WesN
elif [ $region -eq 53 ];then	# Tib
    pscr="-Dh -A1000"
    proj=-JQ85/7
    ann=-Ba20f2WesN
elif [ $region -eq 55 ];then	# ME2
    pscr="-Dh -A3000"
    proj=-JM7
    ann=-Ba5f1WesN
elif [ $region -eq 56 ];then	# ME3
    pscr="-Dh -A3000"
    proj=-JM7
    ann=-Ba10f2WesN
elif [ $region -eq 57 ];then	# TIB2
    pscr="-Dh -A3000"
    proj=-JM7
    ann=-Ba4f2WesN
elif [ $region -eq 50 ];then	# CAR small
    pscr="-Dh -A3000"
    proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    ann=-Ba5f1WesN
elif [ $region -eq 58 ];then	# ALB small
    pscr="-Df "
    proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/7
#    proj=-JM7
    ann=-Ba4f1WesN
elif [ $region -eq 59 ];then	# Northern Anatolia / NAF
    pscr="-Df"
    proj=-JN`echo $reg | gawk '{print(($1+$2)/2)}'`/7
#    proj=-JM7
    ann=-Ba2f.2WesN
elif [ $region -eq 64 ];then
    ann=-Ba2f1WesN
    proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    pscr="-Dh"
elif [ $region -eq 65 ];then
    ann=-Ba5f1WesN
    #proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    proj=-JM6
    pscr="-Dh"
elif [ $region -eq 66 ];then
    ann=-Ba5f1WesN
    #proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    proj=-JM7
    pscr="-Dh"
elif [ $region -eq 67 ];then
    ann=-Ba10f1WesN
    proj=-JM15
    pscr="-Df -A1000"
elif [ $region -eq 68 ];then
    ann=-Ba5f.5WesN
    proj=-JN`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    pscr="-Df -A1000"
elif [ $region -eq 69 ];then
    ann=-Ba5f1WesN
    #proj=-JN`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    proj=-JM7
    pscr="-Df -A1000"
elif [ $region -eq 73 ];then
    ann=-Ba10f2WesN
    proj=-JN`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    pscr="-Di -A1000"
elif [ $region -eq 74 ];then
    ann=-Ba10f2WesN
    proj=-JN`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    pscr="-Df -A1000"
elif [ $region -eq 75 ];then
    ann=-Ba10f2WesN
    proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/10
    pscr="-Df -A1000"
elif [ $region -eq 76 ];then
    ann=-Ba20f5WesN
    #proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    proj=-JM7
    pscr="-Di -A5000"
elif [ $region -eq 77 ];then
    ann=-Ba5f1WesN
    #proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    proj=-JM7
    pscr="-Dh "
elif [ $region -eq 79 ];then
    ann=-Ba20f2WesN
    proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    #proj=-JM7
    pscr="-Dh -A5000"
elif [ $region -eq 80 ];then
    ann=-Ba10f2WesN
    proj=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    #proj=-JM7
    pscr="-Di "
elif [ $region -eq 71 ];then # Congo
    pscr="-Df -A1000"
    ann=-Ba4f2WesN
    proj=-JM7

elif [ $region -eq 81 ];then # Calabria and apenninges
    pscr="-Df -A1000"
    ann=-Ba2f1WesN
    proj=-JM7
elif [ $region -eq 82 ];then # JDF
    pscr="-Df -A1000"
    ann=-Ba2f1WesN
    proj=-JM7
elif [ $region -eq 83 ];then # CAP
    pscr="-Df -A1000"
    ann=-Ba2f1WesN
    proj=-JM7
elif [ $region -eq 84 ];then # anatolia
    pscr="-Df -A1000"
    ann=-Ba2f.5WesN
    proj=-JM7
elif [ $region -eq 85 ];then # massif central
    pscr="-Df"
    ann=-Ba2f1WesN
    proj=-JM7
elif [ $region -eq 86 ];then # iberia
    pscr="-Df -A1000"
    ann=-Ba2f.5WesN
    proj=-JM7
elif [ $region -eq 87 ];then # Alps
    pscr="-Df -A1000"
    ann=-Ba2f1WesN
    proj=-JM7
elif [ $region -eq 88 ];then # South Africa
    pscr="-Df -A1000"
    ann=-Ba4f2WesN
    proj=-JM7

elif [ $region -eq 89 ];then # IND
    pscr="-Df -A1000"
    ann=-Ba5f1WesN
    proj=-JM7

elif [ $region -eq 91 ];then # CRO
    pscr="-Df -A100"
    ann=-Ba1.5WesN
    proj=-JM7

elif [ $region -eq 92 ];then # NIL
    pscr="-Df -A100"
    ann=-Ba10f2WesN
    proj=-JM7
elif [ $region -eq 93 ];then # NIL
    pscr="-Df -A100"
    ann=-Ba5f1WesN
    proj=-JM7
elif [ $region -eq 94 ];then # CAR3
    pscr="-Df -A500"
    ann=-Ba10f2WesN
    proj=-JM7
elif [ $region -eq 95 ];then # 
    pscr="-Di -A20000"
    ann=-Ba20f2WesN
    proj=-JM8
elif [ $region -eq 96 ];then # 
    pscr="-Df -A5000"
    ann=-Ba2f.5WesN
    proj=-JM7
elif [ $region -eq 98 ];then # 
    pscr="-Df -A5000"
    ann=-Ba10f1WesN
    proj=-JM7
elif [ $region -eq 99 ];then
    pscr="-Df -A5000"
    ann=-Ba20f2WeSn
    #proj=-JS`echo $reg | gawk -f reg2midlon.awk`/90/90/9
    proj=-JM7
elif [ $region -eq 100 ];then
    pscr="-Df "
    ann=-Ba1f.1WesN
    #proj=-JS`echo $reg | gawk -f reg2midlon.awk`/90/90/9
    proj=-JM7
elif [ $region -eq 101 ];then
    pscr="-Df -A5000"
    ann=-Ba5f1WesN
    proj=-JM7
elif [ $region -eq 102 ];then
    pscr="-Df -A5000"
    ann=-Ba.5f.1WesN
    proj=-JM7
elif [ $region -eq 103 ];then
    pscr="-Df -A1000"
    ann=-Ba2f.2WesN
    proj=-JM7
elif [ $region -eq 105 ];then
    ann=-Ba2f.2WesN
    proj=-JB`echo $reg1 | gawk -f reg2midlon.awk`/`echo $reg1 | gawk -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.33 -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.66 -f reg2midlat.awk`/10
    #proj=-JM10
    pscr="-Dh"
elif [ $region -eq 106 ];then
    ann=-Ba.1f.01WesN
    proj=-JM7
    pscr="-Df"
elif [ $region -eq 107 ];then
    ann=-Ba1f.2WesN
    proj=-JM7
    pscr="-Df"
elif [ $region -eq 110 ];then 	# GIA
    ann=-Ba20f2WesN
    proj=-JB`echo $reg1 | gawk -f reg2midlon.awk`/`echo $reg1 | gawk -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.33 -f reg2midlat.awk`/`echo $reg1 | gawk -v frac=0.66 -f reg2midlat.awk`/9
    #proj=-JH17.5/7
    pscr="-Di -A5000" # -N1 -N2"
else
    ann=-Ba2f.2WesN
    proj=-JM7
    pscr="-Dh"
fi






if [ $outmode = 0 ];then
    # output is 
    #  1   2 3 4 5  6   7      8          9          10
    # name w e s n reg inc projection annotation pscoast_res
    echo $name $reg $reg1 $inc $proj $ann $pscr
elif [ $outmode = 1 ];then
    # output is 
    # w,s\n e,s\ne,n\nw,n\nw,s\n>\n
    echo $reg | gawk '{print($1,$3);print($2,$3);print($2,$4);print($1,$4);\
	print($1,$3);print(">")}' 
elif [ $outmode = 2 ];then # mid point
    echo $reg |  gawk '{print($1,$3);print($2,$3);
                        print($2,$4);print($1,$4)}' | \
	gawk -f lonlat2xyz.awk | \
	gawk '{x+=$1;y+=$2;z+=$3;n++}END{\
	    print(x/n,y/n,z/n)}' | gawk -f xyz2lonlat.awk |\
    gawk '{print($1,$2)}'
elif [ $outmode = 3 ];then # region in -R format
    echo $reg1
elif [ $outmode = 4 ];then # projection
    echo $proj
elif [ $outmode = 5 ];then # inc
    echo $inc
elif [ $outmode = 6 ];then # ann
    echo $ann
elif [ $outmode = 7 ];then # name
    echo $name
elif [ $outmode = 8 ];then # region in w e s n format
    echo $reg
elif [ $outmode = 8b ];then # region in theta_min theta_max phi_min phi_max [rad]
    echo $reg | gawk -v pif=`pif` -v pi=`pi` \
          '{pih=pi/2;tmin=pih-$4/pif;tmax=pih-$3/pif;pmin=$1/pif;pmax=$2/pif;print(tmin,tmax,pmin,pmax)}'
elif [ $outmode = 9 ];then # overview map, PNG
#    bmc=255/255/255 # color
    r=-R0/360/-90/90 ;
    p=-JN`echo $reg | gawk '{print(($1+$2)/2)}'`/15
    ofile=/tmp/oviewmap.ps
    pscoast $r $p -Dc -A70000 -G243/216/0 -Bg30 -P -K > $ofile
    echo $reg | gawk '{print($1,$3);print($2,$3);print($2,$4);print($1,$4);\
	print($1,$3);print(">")}' | \
	psxy $r $p -M -O -L -Gorange -K >>  $ofile
    pscoast $r $p -Dc -A70000 -W5 -O -K >> $ofile
  
#    psxy $datadir/plate_boundaries/nuvel_without_greenwich_crossing.yx \
#	-M   $r $p -O  -: -W10,magenta >> $ofile
    psxy ~/data/plate_boundaries/bird_PB2002/PB2002_tdiddy.gmt \
	-m   $r $p -O -W10,magenta >> $ofile

    epsmerge --print --postscript -par --orientation Landscape $ofile > /tmp/tmp.ps
    mv /tmp/tmp.ps $ofile
#    epstopdf $ofile; rm $ofile ; echo $0: output in oviewmap.pdf
#    /usr/bin/convert $ofile -transparent white oviewmap.$name.png
    make_transparent $ofile 1 1 2 1 1 2> /dev/null
    mv /tmp/oviewmap.trans*png $HOME/tmp/
#    rm $ofile
    echo $0: output in `ls $HOME/tmp/oviewmap.trans*.png`

elif [ $outmode = 10 ];then # detailed  map

    pscoast $reg1 $proj $pscr -N1 -G200 $ann -P -K > regmap.ps
    if [ -s tracks.lonlat ];then
	psxy tracks.lonlat    -Sa0.1  $reg1 $proj -O  -K -G200/0/0 >> regmap.ps

    fi
    psbasemap $reg1 $proj -L120/-38/-38/1000 -O -K >> regmap.ps
    psxy $datadir/plate_boundaries/nuvel_without_greenwich_crossing.yx \
	-M   $reg1 $proj -O  -: -W1/000/156/070 >> regmap.ps

    echo $0: output in regmap.ps
elif [ $outmode = 11 ];then # overview map, PDF and EPS
    r=-R0/360/-90/90 
    p=-JH`echo $reg | gawk '{print(($1+$2)/2)}'`/7
    #    p=-JQ180/7
    pscoast $r $p -Dc -A7000 -Gcyan -Bg30 -P -K > oviewmap.eps
    echo $reg | gawk -f reg2box.awk | gawk '{print($1,$2)}' | \
	psxy -W5/$bmc $r $p -M -O \
	    -Gorange -K >>  oviewmap.eps
    pscoast $r $p -Dc -A7000 -W0.5 -O -K >> oviewmap.eps
    psxy $datadir/plate_boundaries/nuvel_without_greenwich_crossing.yx \
	-M   $r $p -O  -: -W8,magenta >> oviewmap.eps
    modifybb oviewmap.eps #70 70 580 330
    make_transparent oviewmap.eps 
#    epstopdf oviewmap.eps
#    echo $0: output in oviewmap.pdf and oviewmap.eps
elif [ $outmode = 12 ];then
    echo $reg | gawk '{print(($1+$2)/2)}'
elif [ $outmode = 13 ];then
    echo $pscr
elif [ $outmode = 14 ];then
    echo $reg | gawk '{f=57.2957795130823;\
              print((90-$4)/f,(90-$3)/f,$1/f,$2/f);}'
elif [ $outmode = 15 ];then # mid point in lon lat
    echo $reg | gawk '{print(($1+$2)/2,($3+$4)/2)}'
else
    echo $0: outmode $outmode undefined
    exit
fi

