#!/bin/bash
#
# scripts to test binning / sampling of Kostrov and stress inversions
#
clear=${1-1}


cat=cheng25.aki;aki=1
#reg=`minmax -fg -I $cat`
reg=-R230/250/29/44
echo $reg | gawk -f reg2wesn.awk > tmp.dat
read w e s n < tmp.dat ; rm tmp.dat

#dy=0.1				# spacing for binning
dy=0.2				# spacing for binning

# adjust for mean lat
dx=`echo $dy $s $n | gawk  'BEGIN{pif=57.29577951308232087;}{lat=($2+$3)/2/pif;printf("%.2f",$1*cos(lat))}'`

dy_km=`echo $dy | gawk '{printf("%.1f",$1*111.19492664/1.2)}'` # distance in km sort of
dy_km2=`echo $dy_km | gawk '{print($1*3)}'`

mmin=3;mmax=6.75;dmax=15;dmin=-5

nmink=8			  # min number

dweight1=1;nmin1=$nmink;dist_max1=$dy_km # distance based
dweight2=1;nmin2=-$nmink;dist_max2=$dy_km  #  number based, allowing for a bit more distance

echo $0: $cat $reg $w $e $s $n mag $mmin $mmax dep $dmin $dmax
echo $0: $dx $dy $dy_km $dy_km2


if [ $clear -eq 1 ];then
    rm kostrov.$dx.$dy.0.norm.dat nsample1.$dx.$dy.0.norm.dat   nsample2.$dx.$dy.0.norm.dat
fi


if [ ! -s kostrov.$dx.$dy.0.norm.dat ];then
    # regular binning
    bin/bin_catalog  $cat $dx $mmin $mmax 0 $w $e $s $n $dmax $aki 0 $dmin 0 kostrov $dy $nmink
else
    echo $0: reusing kostrov.$dx.$dy.0.norm.dat 
fi



if [ ! -s  nsample1.$dx.$dy.0.norm.dat ];then
    bin/nsample_catalog  $cat $dx $mmin $mmax $w $e $s $n $dmax $aki $dweight1 $nmin1 $dist_max1 $dmin 0 nsample1 $dy
else
    echo $0: reusing nsample1.$dx.$dy.0.norm.dat
fi


if [ ! -s  nsample2.$dx.$dy.0.norm.dat ];then
    bin/nsample_catalog  $cat $dx $mmin $mmax $w $e $s $n $dmax $aki $dweight2 $nmin2 $dist_max2 $dmin 0 nsample2 $dy
else
    echo $0: reusing  nsample2.$dx.$dy.0.norm.dat
fi



# simple plots

makecpt -Croma -T-0.3/0.3/0.03 > tmp.cpt
makecpt -Clajolla  -T0/1/0.1 > tmp.f.cpt

om=1

if [ $om = 1 ];then
    reg=-R-10/3/-2/2.75
    greg=-R-118.5/-115.5/32.5/36
    proj=-JOa-116.5/33.5/143/20
    psc_loc=-D5/8/3/.15h
    psc_loc2=-D15/8/3/.15h
    ann=af.5a2g5
    #    scale=0.15
    scale=0.3
else
    reg=-R$w/$e/$s/$n
    greg=$reg
    proj=-JM7
    psc_loc=-D6.35/7.5/3/.2
    psc_loc2=-D5.7/7.5/3/.2
    ann=af.15a1
    #    scale=0.25
    scale=0.5
fi

fs=""
for s in  kostrov nsample1 nsample2;do
    sname=$s
    if [ $s = kostrov ];then
	alabel="bin"
    elif [ $nsample1 ];then
	alabel="dbin"
    else
	alabel="nbin"
    fi
    for m in kostrov stress ;do
	if [ $m = kostrov ];then
	    end=0.norm
	else
	    end=s
	fi
	sfile=$sname.$dx.$dy.$end.dat
	
	if [ ! -s $sfile ];then
	    echo $0: $sfile not found
	    exit
	fi
	if [ $end = 0.norm ];then
	    label=Kostrov
	elif [ $end = s ];then
	    label=Michael
	elif [ $end = ds ];then
	    label="Vavrycuk @~m@~=0.6"
	elif [ $end = bs ];then
	    label="Vavrycuk @~m@~@-bf@-"
	else
	    label=$end
	fi
    
	ofile=simple.$s.$m.ps

	
	pscoast -Df -S200 -G120 -W0.5 $reg $proj -P -K -B$ann:."$s, $m": > $ofile
	psxy $datadir/plate_boundaries/bird_PB2002/PB2002_tdiddy.gmt  -m  \
	     $reg -fg  $proj  -O -K   -W1,darkblue  >> $ofile
	psxy $datadir/faults/scitex.faults $reg $proj -O -W0.5,darkblue -m -K >> $ofile
	psscale $psc_loc  -B.1/:@~e@~@-m@-: -E -O -K -Ctmp.cpt >> $ofile
	
	# 	m: Seismic (full) moment tensor:
	#           X Y depth mrr mtt mff mrt mrf mtf exp [newX newY] [event_title].
	gawk '{print($1,$2,$3,$4,$5,$6)}' $sfile | gawk -f tensornorm.awk  > tmp.norm
	gawk '{print($1,$2,$3,$4,$5,$6,$7,$8)}' $sfile > tmp.1
	paste tmp.1 tmp.norm | gawk '{print($7,$8,($4+$6)/2/$9,$1,$4,$6,$2,$3,$5,22,$7,$8)}' > tmp.plot
	if [ $end = bs ];then
	    gawk '{print($7,$8,$11)}' $sfile | psxy $reg $proj -t30 -SS.4  -O -K  -Ctmp.f.cpt >> $ofile
	    psscale $psc_loc2  -B.2/:@~m@~:  -O -K -Ctmp.f.cpt >> $ofile
	fi
	rm tmp.norm tmp.1
	# moment tensor
	psmeca tmp.plot $reg $proj  -L0.25 -W0.25 -D-1e5/1e5  -Ctmp.cpt "-Sm"$scale"/-1"  -O -K >> $ofile
	# overlay double couple
	psmeca tmp.plot $reg $proj  -L0.25 -W0.25 -D-1e5/1e5  "-Sd"$scale  -O  -T0 >> $ofile
	rm tmp.plot 
	modifybb $ofile
	#gv $ofile;exit
	fs="$fs $ofile"
	((nplot=nplot+1))
    done
done

#exit
epsmerge -par -x 2 -y 3 --orientation Portrait $fs > stress_comp.ps
psconvert -Tf stress_comp.ps
rm $fs stress_comp.ps



